import { mount } from '@vue/test-utils'
import { describe, it, expect } from 'vitest'
import { createVuetify } from 'vuetify'
import * as components from 'vuetify/components'
import * as directives from 'vuetify/directives'
import SongCard from '../../src/components/songs/SongCard.vue'

/**
 * Unit test suite for the SongCard.vue component.
 * Validates atomic rendering based on injected properties (props).
 */
const vuetify = createVuetify({ components, directives })

describe('SongCard.vue - Unit Rendering', () => {
    /**
     * Mock dataset configuration.
     * Compliant with the domain-specific track interface.
     */
    const mockSong = {
        trackName: 'Test Song',
        artistName: 'Test Artist',
        artworkUrl: 'https://example.com/image.jpg'
    }

    it('should correctly render track metadata as text nodes', () => {
        const wrapper = mount(SongCard, {
            props: { song: mockSong },
            global: { plugins: [vuetify] }
        })

        // Assert presence of mandatory string literals in the rendered output.
        expect(wrapper.text()).toContain('Test Song')
        expect(wrapper.text()).toContain('Test Artist')
    })

    it('should bind the correct source URL to the image attribute', () => {
        const wrapper = mount(SongCard, {
            props: { song: mockSong },
            global: { plugins: [vuetify] }
        })

        /**
         * Resource binding validation.
         * Locates the internal img element generated by the VImg component.
         */
        const img = wrapper.find('img')
        expect(img.attributes('src')).toBe('https://example.com/image.jpg')
    })

    it('should assign the designated stylistic class to the component root', () => {
        const wrapper = mount(SongCard, {
            props: { song: mockSong },
            global: { plugins: [vuetify] }
        })

        // Verify CSS class declaration integrity.
        expect(wrapper.classes()).toContain('song-card')
    })
})